// Self-test for no-inline-scripts.mjs: spawns the hook by path with a Bash
// tool envelope on stdin (or a PowerShell one, for a [command, tool] entry)
// and checks the exit code, the stderr marker and the elapsed time. Run from
// the repository root:
//   node scripts/no-inline-scripts.test.mjs
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const hook = join(dirname(fileURLToPath(import.meta.url)), 'no-inline-scripts.mjs');
const MAX_MS = 2000;
const blocked = [
  // node family: inline flags in every position and quoting the shell allows
  'node -e "const r=JSON.parse(require(\'fs\').readFileSync(0,\'utf8\'));console.log(r.x)"',
  'cat out.json | node -e "const r=JSON.parse(require(\'fs\').readFileSync(0,\'utf8\'));console.log(r)"',
  'node C:/x/helper.js a b || node -e "console.log(1)"',
  'node --eval "1+1"',
  'node --eval="1+1"',
  'node -p "process.versions.node"',
  'node -pe "1"',
  'node.exe -e "1"',
  'node "-e" "1"',
  'MSYS_NO_PATHCONV=1 node -e "1"',
  'env FOO=1 node -e "1"',
  'node --input-type=module -e "import x from \'y\'"',
  'node -r dotenv/config -e "x"',
  'node --require ./setup.js --eval "x"',
  '/usr/bin/node -e "1"',
  '"C:/Program Files/nodejs/node.exe" -e "1"',
  'bun -e "1"',
  'deno eval "1"',
  'npm test && node -e "2"',
  '(node -e "1")',
  'x=$(node -e "console.log(1)")',
  'echo `node -p 1`',
  // python: -c in every spelling, including attached bodies and clusters
  'python -c "print(1)"',
  'python3 -c "import sys; print(sys.argv)"',
  'python3.12 -c "print(1)"',
  'py -3 -c "print(1)"',
  'python -Bc "print(1)"',
  "python -c'print(1)'",
  'python -cprint(1)',
  // a program read from stdin is an inline body too
  'node <<\'EOF\'\nconsole.log(1)\nEOF',
  'python - <<EOF\nprint(1)\nEOF',
  'python <<EOF\nprint(1)\nEOF',
  'bash <<\'EOF\'\necho hi\nEOF',
  'bash 2>&1 <<\'EOF\'\necho hi\nEOF',
  'pwsh -NoProfile <<\'EOF\'\nGet-Date\nEOF',
  'cat <<\'EOF\' | node\nconsole.log(1)\nEOF',
  'cat <<\'EOF\' | python -\nprint(1)\nEOF',
  'echo "print(1)" | python',
  'printf "console.log(1)" | node',
  'cat script.js | node --enable-source-maps',
  'cat script.js |& node',
  'node -',
  'node <<< "console.log(1)"',
  'sh <<EOF\necho hi\nEOF',
  'zsh <<EOF\necho hi\nEOF',
  'powershell -NoProfile <<EOF\nGet-Date\nEOF',
  'bash &>/dev/null <<EOF\necho hi\nEOF',
  'cat x.ts | deno run -',
  'cat x.ts | deno run',
  'deno --quiet eval "1"',
  // shapes ahead of the command word: keywords, wrappers, earlier herestrings
  'if node -e "1"; then echo y; fi',
  'if ! node -e "1"; then echo y; fi',
  'for f in *.json; do node -e "console.log(1)" "$f"; done',
  'while true; do python -c "print(1)"; done',
  '{ node -e "1"; }',
  '! node -e "1"',
  'timeout 30 node -e "1"',
  'find . | xargs node -e "1"',
  'sudo -u me node -e "1"',
  'env -i node -e "1"',
  'nice -n 10 node -e "1"',
  'cat <<< "x"\nnode -e "1"',
  'read -r v <<< "$x"\necho "$v"\nnode -e "1"',
  '"C:\\Program Files\\nodejs\\node.exe" -e "1"',
  // substitutions inside double quotes, arithmetic shifts, function bodies, remaining wrappers
  'echo "version: $(node -p \'process.version\')"',
  'v="$(node -e \'console.log(1)\')"',
  'echo "v=$(python -c \'print(1)\')"',
  'echo "`node -e 1`"',
  'grep x <<< "$(node -e 1)"',
  'cat <<< $(node -e "1")',
  'echo "$(date)"; node -e "1"',
  'echo "a $(echo "b $(node -e 1)")"',
  'function f { node -e "1"; }',
  'f() { node -e "1"; }',
  'case $x in (a) node -e "1";; esac',
  'case $x in a) node -e "1";; esac',
  '(cd C:/x && node -e "1")',
  'echo $((1<<2))\nnode -e "1"',
  'stdbuf -oL node -e "1"',
  'deno repl --eval "console.log(1)"',
  'node -e "$(unclosed',
  'echo "$(node -e 1',
  // a shell -c or pwsh -Command body of more than one statement, in every spelling
  'bash -c "echo a; echo b"',
  "bash -lc 'echo a; echo b'",
  'bash -ec "set -x; echo a"',
  'bash -o pipefail -c "echo a; echo b"',
  'sh -c "echo a\necho b"',
  'zsh -c "echo a; echo b"',
  "'C:/Program Files/Git/bin/bash.exe' -lc 'echo a; echo b'",
  'pwsh -NoProfile -Command "$a = 1; Write-Host $a"',
  'pwsh -NoProfile -ExecutionPolicy Bypass -Command "$a = 1; Write-Host $a"',
  'pwsh -NoProfile -c "$a = 1; Write-Host $a"',
  'pwsh -NoProfile -command "$a = 1; Write-Host $a"',
  'pwsh -NoProfile -Comm "$a = 1; Write-Host $a"',
  'pwsh -wd C:/x -Command "$a = 1; Write-Host $a"',
  'pwsh -Command "Get-Date\nGet-Location"',
  'powershell -NoProfile -Command "$a = 1; Write-Host $a"',
  'pwsh -NoProfile -EncodedCommand ZwBjAGgAbwA=',
  'pwsh -e ZwBjAGgAbwA=',
  'pwsh -ec ZwBjAGgAbwA=',
  'pwsh -NoProfile -Command -',
  'bash -c -',
  `bash -c "${'x'.repeat(201)}"`,
  `pwsh -Command "${'x'.repeat(201)}"`,
  'node x.js || bash -c "echo a; echo b"',
  'bash -c "echo a; echo b" _ arg1',
  'bash -c "sleep 1 & echo b"',
  'bash -O extglob -c "echo a; echo b"',
  'bash +o posix -c "echo a; echo b"',
  'pwsh -cwa "$a = 1; Write-Host $a" x',
  'pwsh -NoProfile -CommandWithArgs "$a = 1; Write-Host $a" x',
  'pwsh -EncodedArguments AAAA -EncodedCommand ZwBjAGgAbwA=',
  // a body is read by the interpreter that receives it: a backslash escapes in bash and is a path separator in pwsh
  "pwsh -NoProfile -Command 'Write-Host \"C:\\Git\\\"; Get-Date'",
  "pwsh -NoProfile -Command 'Write-Host \"a\\\"; Get-Date'",
  "bash -c 'echo \"a`\"; echo b'",
  // the same shapes issued through the PowerShell tool, in its dialect
  ['node -e "const a = 1; console.log(a)"', 'PowerShell'],
  ['C:\\tools\\node.exe -e "1"', 'PowerShell'],
  ['& "C:\\Python312\\python.exe" -c "print(1)"', 'PowerShell'],
  ["& 'C:\\Program Files\\nodejs\\node.exe' -p 1", 'PowerShell'],
  ['python -c "print(1)"', 'PowerShell'],
  ['py -3 -c "print(1)"', 'PowerShell'],
  ['"print(1)" | python', 'PowerShell'],
  ['"print(1)" | python -', 'PowerShell'],
  ['Get-Content x.js | node', 'PowerShell'],
  ['node -e "a`nb"', 'PowerShell'],
  ['pwsh -NoProfile -Command "$a = 1; Write-Host $a"', 'PowerShell'],
  ['& pwsh -NoProfile -Command "$a = 1; Write-Host $a"', 'PowerShell'],
  ['Set-Location C:\\x; node -e "1"', 'PowerShell'],
  ['$v = $(node -p "1")', 'PowerShell'],
  ['bash -lc "echo a; echo b"', 'PowerShell'],
  ["& 'C:\\Program Files\\Git\\bin\\bash.exe' -lc 'echo a; echo b'", 'PowerShell'],
  ["pwsh -NoProfile -Command 'Write-Host \"C:\\Git\\\"; Get-Date'", 'PowerShell'],
  ['pwsh -Command "Get-Date`nGet-Location"', 'PowerShell'],
  // scriptblocks nest commands, and a block passed as the command is counted as a body
  ['try { node -e "1" } catch { Write-Host x }', 'PowerShell'],
  ['Invoke-Command -ScriptBlock { node -e "1" }', 'PowerShell'],
  ['Get-ChildItem | Where-Object { $_.Length } | ForEach-Object { python -c "print(1)" }', 'PowerShell'],
  ['gci | % { node -e "1" }', 'PowerShell'],
  ['if ($x) { node -e "1" }', 'PowerShell'],
  ['& { node -e "1" }', 'PowerShell'],
  ['foreach ($f in $files) { bash -c "echo a; echo b" }', 'PowerShell'],
  ['pwsh -NoProfile -Command { Get-Date; Get-Location }', 'PowerShell'],
  ['& "C:\\Program Files\\PowerShell\\7\\pwsh.exe" -NoProfile -Command { $a = 1; Write-Host $a }', 'PowerShell'],
  ['pwsh -Command { node -e "1" }', 'PowerShell'],
  ['pwsh -Command { Get-Date; Get-Location', 'PowerShell'],
];
const allowed = [
  'node --test tests/setup.test.js',
  'node skills/ready/ready.js C:/Git/nightshift',
  'node "C:/Users/me/.claude/plugins/cache/x/internal/runtime/cli.js" C:/Git/x C:/tmp/request.json',
  'node C:/Git/x/tools/release-gate.js --baseline abc --head HEAD',
  'node -r dotenv/config app.js',
  'node --enable-source-maps dist/main.js',
  'node --input-type=module app.mjs',
  'node --version',
  'node server.js -p 3000',
  'node cli.js -e production',
  'node x.js \\\n        --flag a \\\n        --flag b \\\n        --flag c',
  'node' + ' '.repeat(40) + 'x.js',
  'npm run build',
  'npx eslint .',
  'git commit -m "fix: thing" -- file.js',
  'git commit -m "use node -e less"',
  'echo node -e is banned',
  'echo hello',
  'grep -e pattern file.txt',
  'sed -e "s/a/b/" file.txt',
  'sed -n "1,5p" file.txt',
  'cat <<\'EOF\' > data.txt\nplain data\nEOF',
  'cat <<\'EOF\' > data.txt\nnode -e "looks inline but is data"\nEOF',
  'python read.py <<EOF\n{"a":1}\nEOF',
  'node read-stdin.js <<\'EOF\'\nplain data\nEOF',
  'bash script.sh <<EOF\ninput\nEOF',
  'pwsh -NoProfile -File C:/x/.tmp/script.ps1 <<EOF\ninput\nEOF',
  'echo "x" | node C:/x/read-stdin.js',
  'cat data.json | python process.py',
  'cat file | jq -r ".a"',
  'pwsh -NoProfile -Command "Get-Date"',
  'pwsh -NoProfile -File C:/x/.tmp/script.ps1',
  'python C:/x/script.py --flag',
  'python3 -m pytest tests/',
  'python -m pip install -c constraints.txt -r requirements.txt',
  'python -m pytest -c pytest.ini tests/',
  'python -mcalendar',
  'python manage.py test -c',
  'python -Wc script.py',
  'python -m pytest \\\n' + '    tests/a.py \\\n'.repeat(10),
  'deno run app.ts',
  'printf "%s\\n" "node -e is banned"',
  'rg --crlf -n "node -e" docs/',
  'here <<< "string"',
  'cat <<<"node -e"',
  'jq -r ".a" <<< "$json"\npython process.py',
  'node < script.js',
  'if [ -f x ]; then node build.js; fi',
  'for f in *.json; do node check.js "$f"; done',
  'timeout 30 node server.js',
  'find . -name "*.js" | xargs node lint.js',
  'deno --version',
  'echo "a\\"b" | node handle.js',
  'echo "version: $(node version.js)"',
  'v="$(node C:/x/cli.js --json)"; echo "$v"',
  'echo "$(date)"; node build.js',
  'echo $((1<<2))\nnode build.js',
  'function f { node build.js; }',
  'f() { node build.js; }',
  'stdbuf -oL node server.js',
  'echo x | node $(git rev-parse --show-toplevel)/x.js',
  'echo x | node "$(git rev-parse --show-toplevel)/x.js"',
  'cat req.json | python $(git rev-parse --show-toplevel)/tools/t.py',
  'cat x | node $(pwd)',
  // one-statement -c and -Command bodies, which the rule allows
  "bash -c 'echo hi'",
  "sh -c 'ls | wc -l'",
  'bash -c "grep a && echo found"',
  "bash -c 'echo \"a;b\"'",
  'bash -c "echo \'a;b\'"',
  "bash -c 'echo a\\;b'",
  'bash -c "echo a\\\nb"',
  'bash -c',
  'bash --norc -c "echo hi"',
  "pwsh -NoProfile -Command 'Get-Date'",
  "pwsh -NoProfile -c 'Get-Date'",
  'pwsh -NoProfile -Command Get-Date',
  'pwsh -NoProfile -ExecutionPolicy Bypass -Command "Get-ChildItem | Measure-Object"',
  "pwsh -NoProfile -Command \"Write-Host 'a;b'\"",
  'pwsh -NoProfile -Command "Write-Host `"a;b`""',
  'pwsh -NoProfile -ExecutionPolicy Bypass -File C:/x/.tmp/script.ps1 -Name value',
  'pwsh -Version',
  'pwsh -NoProfile -Command',
  'powershell -NoProfile -Command "Get-Date"',
  `pwsh -Command "${'x'.repeat(200)}"`,
  'bash -c "echo \\"$1\\"" _ arg1',
  'bash -c "grep a && echo found & "',
  'bash -c "cmd 2>&1"',
  'bash -c "cmd &>/dev/null"',
  'bash -c "cmd |& tee log"',
  "bash -c 'echo \"a\\\";b\"'",
  "pwsh -NoProfile -Command 'Write-Host \"a`\";b\"'",
  'pwsh -NoProfile -Command "Get-ChildItem C:\\Git\\"',
  'pwsh -cwa "Write-Host $args" x y',
  // PowerShell tool text is itself a script; only nested interpreters count
  ['$a = 1; Write-Host $a; Get-ChildItem', 'PowerShell'],
  ['node C:\\x\\build.js', 'PowerShell'],
  ['& "C:\\Program Files\\nodejs\\node.exe" build.js', 'PowerShell'],
  ['Get-Content data.json | node handle.js', 'PowerShell'],
  ['git commit -m "use node -e less"', 'PowerShell'],
  ['Write-Host "a`tb"; node build.js', 'PowerShell'],
  ['python -m pytest tests\\', 'PowerShell'],
  ['pwsh -NoProfile -Command "Get-Date"', 'PowerShell'],
  ['pwsh -NoProfile -File C:\\x\\.tmp\\script.ps1', 'PowerShell'],
  ['$v = $(node build.js)', 'PowerShell'],
  ['Write-Host "value: $(node version.js)"', 'PowerShell'],
  ['try { node build.js } catch { Write-Host x }', 'PowerShell'],
  ['Get-ChildItem | ForEach-Object { python check.py $_ }', 'PowerShell'],
  ['pwsh -NoProfile -Command { Get-Date }', 'PowerShell'],
  ['Write-Host "${env:PATH}"; node build.js', 'PowerShell'],
  ['$h = @{ a = 1; b = 2 }; node build.js', 'PowerShell'],
  ['Write-Host "a`nb"; node build.js', 'PowerShell'],
];

let failures = 0;
const run = entry => {
  const [command, tool] = Array.isArray(entry) ? entry : [entry, 'Bash'];
  const started = Date.now();
  const result = spawnSync(process.execPath, [hook], { input: JSON.stringify({ tool_name: tool, tool_input: { command } }), encoding: 'utf8', windowsHide: true, timeout: 10000 });
  return { ...result, ms: Date.now() - started };
};
for (const entry of blocked) {
  const result = run(entry);
  if (result.status !== 2 || !result.stderr.includes('Blocked by no-inline-scripts hook')) { failures++; console.log('NOT BLOCKED:', JSON.stringify(entry), 'exit', result.status); }
  if (result.ms > MAX_MS) { failures++; console.log('SLOW:', JSON.stringify(entry), result.ms, 'ms'); }
}
for (const entry of allowed) {
  const result = run(entry);
  if (result.status !== 0) { failures++; console.log('WRONGLY BLOCKED:', JSON.stringify(entry), 'exit', result.status, result.stderr.trim().split('\n')[0]); }
  if (result.ms > MAX_MS) { failures++; console.log('SLOW:', JSON.stringify(entry), result.ms, 'ms'); }
}
const envelopes = [
  ['non-shell tool', JSON.stringify({ tool_name: 'Read', tool_input: { file_path: 'node -e' } })],
  ['inherited property as a tool name', JSON.stringify({ tool_name: 'constructor', tool_input: { command: 'node -e 1' } })],
  ['malformed JSON', 'not json'],
  ['empty stdin', ''],
  ['missing tool_input', JSON.stringify({ tool_name: 'Bash' })],
  ['non-string command', JSON.stringify({ tool_name: 'Bash', tool_input: { command: 42 } })],
];
for (const [name, input] of envelopes) {
  const result = spawnSync(process.execPath, [hook], { input, encoding: 'utf8', windowsHide: true, timeout: 10000 });
  if (result.status !== 0) { failures++; console.log('ENVELOPE NOT PASSED THROUGH:', name, 'exit', result.status); }
}
console.log(`${blocked.length} blocked, ${allowed.length} allowed, ${envelopes.length} envelope cases; failures: ${failures}`);
process.exit(failures === 0 ? 0 : 1);
